config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root to: "trader/stocks#index"

  namespace :admin do
    root to: 'dashboard#index', as: :root

    resources :dashboard, only: [:index]
    resources :users, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      collection do
        get :pending_approvals
      end
      member do
        patch :approve
      end
    end
    resources :transactions, only: [:index]
  end

  namespace :trader do
    resources :users, only: [:show, :index] do
      resources :stocks, only: [:index]
      resources :transactions, only: [:index, :new, :create]
    end
  end

  match "*unmatched", to: "errors#not_found", via: :all

  match "*unmatched", to: "errors#not_found", via: :all
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  has_many :transactions, dependent: :destroy
  has_many :stocks, dependent: :destroy

  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 6 }, allow_blank: true
  validates :name, presence: true

  def active_for_authentication?
    super && is_approved?
  end

  def inactive_message
    is_approved? ? super : :not_approved
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout "admin"
  before_action :set_user, only: [:show, :edit, :update, :destroy, :approve]
  before_action :authorize_admin!
  rescue_from ActiveRecord::RecordNotFound, with: :user_not_found

  def index
    @all_users = User.where(is_admin: false).order(created_at: :desc).page(params[:page]).per(5)
    @total_users = User.where(is_approved: true).where.not(confirmed_at: nil).count
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.is_approved = true
    if @user.save
      redirect_to admin_users_path, notice: "User successfully created"
    else
      render :new, status: :unprocessable_entity, alert: "Failed creating user, try again"
    end
  end

  def show; end

  def edit; end

  def update
    @user.assign_attributes(user_params)
    @user.skip_reconfirmation!
    if @user.save
      redirect_to admin_user_path(@user), notice: "User updated successfully"
    else 
      render :edit, status: :unprocessable_entity, alert: "Unable to update user"
    end
  end
  
  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice: "User deleted"
    else
      redirect_to admin_users_path, alert: "Failed to delete user"
    end
  end

  def pending_approvals
    @pending_users = User.where(is_approved: false).where.not(confirmed_at: nil)
  end
  
  def approve  
    @user.update(is_approved: true)
    UserMailer.with(user: @user).approval_email.deliver_now
    redirect_to pending_approvals_admin_users_path, notice: "User approved and can now log in"
  end

  private
  
  def user_params
    permitted = params.require(:user).permit(:name, :email, :password, :password_confirmation)
    if permitted[:password].blank?
      permitted.delete(:password)
      permitted.delete(:password_confirmation)
    end
    permitted
  end
  
  def set_user
    @user = User.find(params[:id])
  end

  def user_not_found
    redirect_to admin_users_path, alert: "An error occurred while trying to find the information you're getting" 
  rescue StandardError => e
    redirect_to admin_users_path, alert: "An error occurred while trying to find the user."
  end
end

app/controllers/trader/users_controller.rb
class Trader::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_stock_data
  before_action :trader_check
  layout "trader"
  def show; end

  def index
    redirect_to trader_user_path(current_user)  
  end
end 

app/helpers/admin/user_helper.rb
module Admin::UserHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/trader/user_helper.rb
module Trader::UserHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/users/_form.html.erb
<%= form_with model: [:admin, @user] do |form| %>

<div class="max-w-md mx-auto p-6 bg-gray-100 shadow-md border rounded-md mt-8">
  <h1 class="text-2xl font-semibold text-center mb-6">
    <%= @user.new_record? ? "Create User" : "Edit User" %>
  </h1>

  <div class="mb-4">
    <%= form.label :name, class: "block text-gray-700 font-medium" %>
    <%= form.text_field :name, value: @user.name, class: "w-full p-2 border border-gray-300 rounded-md" %>
    <% @user.errors.full_messages_for(:name).each do |message| %>
      <div class="text-red-600 text-sm"><%= message %></div>
    <% end %>
  </div>

  <div class="mb-4">
    <%= form.label :email, class: "block text-gray-700 font-medium" %>
    <%= form.text_field :email, value: @user.email, class: "w-full p-2 border border-gray-300 rounded-md" %>
    <% @user.errors.full_messages_for(:email).each do |message| %>
      <div class="text-red-600 text-sm"><%= message %></div>
    <% end %>
  </div>

  <div class="mb-4">
    <%= form.label :password, class: "block text-gray-700 font-medium" %>
    <%= form.password_field :password, class: "w-full p-2 border border-gray-300 rounded-md" %>
    <% @user.errors.full_messages_for(:password).each do |message| %>
      <div class="text-red-600 text-sm"><%= message %></div>
    <% end %>
  </div>

  <div class="mt-6">
    <%= form.submit @user.new_record? ? "Create User" : "Update User", class: "w-full py-2 bg-blue-600 text-white font-semibold rounded-md hover:bg-blue-700 transition" %>
  </div>

</div>

<% end %>

app/views/admin/users/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Admin::Users#create</h1>
  <p>Find me in app/views/admin/users/create.html.erb</p>
</div>

app/views/admin/users/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">Admin::Users#destroy</h1>
  <p>Find me in app/views/admin/users/destroy.html.erb</p>
</div>

app/views/admin/users/edit.html.erb
<div>
  <%= render "form", user: @user, class: "mx-auto" %>

  <div class="mt-6 flex justify-center space-x-4">
    <%= link_to "Back to Users", admin_users_path, class: "bg-gray-300 text-gray-800 px-4 py-2 rounded-lg hover:bg-gray-400 transition duration-150" %>
  </div>

</div>

app/views/admin/users/index.html.erb
<%= content_for :title, "Users" %>

<div class="container mx-auto p-4">
  <div class="flex items-center justify-between mb-6">
    <h1 class="text-3xl font-bold text-purple-900">Users</h1>
    <div class="flex items-center space-x-4">
      <p class="text-lg font-semibold text-gray-700">Total: <%= @total_users %></p>
      
      <%= link_to 'Add User', new_admin_user_path, class: 'bg-green-500 text-white px-6 py-2 rounded-lg hover:bg-green-700 transition duration-300' %>
    </div>
  </div>

  <% if @all_users.any? %>
    <div class="overflow-x-auto shadow-lg rounded-lg border border-gray-900">
      <table class="min-w-full table-auto">
        <thead class="bg-gray-700 text-white">
          <tr>
            <th class="px-4 py-2 text-left">Name</th>
            <th class="px-4 py-2 text-left">Email</th>
            <th class="px-4 py-2 text-left">Registered at</th>
            <th class="px-4 py-2 text-left">Manage</th>
          </tr>
        </thead>
        <tbody>
          <% @all_users.each do |user| %>
            <tr class="bg-gray-50 hover:bg-gray-100">
              <td class="px-4 py-1"><%= user.name %></td>
              <td class="px-4 py-1"><%= user.email %></td>
              <td class="px-4 py-1"><%= user.created_at.strftime("%b %d, %Y") %></td>
              <td class="px-4 py-1">
                <div class="flex space-x-3">
                  <%= link_to "Show", admin_user_path(user), class: "text-blue-600 hover:text-blue-800 px-3 py-1 border border-blue-600 rounded-md transition-colors duration-200" %><i class="fas fa-eye"></i>

                  <%= link_to "Edit", edit_admin_user_path(user), class: "text-yellow-600 hover:text-yellow-800 px-3 py-1 border border-yellow-600 rounded-md transition-colors duration-200" %>
                  <%= link_to "Delete", admin_user_path(user), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this user?" }, class: "text-red-600 hover:text-red-800 px-3 py-1 border border-red-600 rounded-md transition-colors duration-200" %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="mt-6">
      <%= paginate @all_users %>
    </div>
  <% else %>
    <div class="text-center p-8 text-gray-500 text-lg border rounded-lg shadow-lg">
      <p>No users found.</p>
    </div>
  <% end %>
</div>

app/views/admin/users/new.html.erb
<%= render "form", user: @user %>

app/views/admin/users/pending_approvals.html.erb
<div class="container mx-auto p-1 max-w-60">
  <h2 class="text-3xl font-bold text-purple-900 mb-6">Pending User Approvals</h2>

  <div class="overflow-x-auto shadow-lg rounded-lg border border-gray-900">
    <table class="min-w-full table-auto">
      <thead class="bg-gray-700 text-white">
        <tr>
          <th class="px-4 py-2 text-left">Email</th>
          <th class="px-4 py-2 text-left">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @pending_users.each do |user| %>
          <tr class="bg-gray-50 hover:bg-gray-100">
            <td class="px-4 py-1"><%= user.email %></td>
            <td class="px-4 py-1">
              <div class="flex space-x-3">
                <%= link_to "Approve", approve_admin_user_path(user), 
                            data: { turbo_method: :patch, turbo_confirm: "Approve this user?" },
                            class: "text-green-600 hover:text-green-800 px-3 py-1 border border-green-600 rounded-md transition-colors duration-200" %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="max-w-md mx-auto p-4 sm:p-6 border border-gray-300 rounded-lg bg-gray-50 mt-8">
  <h1 class="text-2xl sm:text-3xl text-center text-gray-800 mb-4">User Information</h1>

  <div class="pb-4 mb-4 sm:mb-6 border-b border-gray-300 px-4">
    <h2 class="text-lg sm:text-xl text-gray-600">Name:</h2>
    <p class="text-base sm:text-lg text-gray-700"><%= @user.name %></p>
  </div>

  <div class="pb-4 mb-4 sm:mb-6 border-b border-gray-300 px-4">
    <h2 class="text-lg sm:text-xl text-gray-600">Email:</h2>
    <p class="text-base sm:text-lg text-gray-700"><%= @user.email %></p>
  </div>

  <div class="pb-4 px-4">
    <h2 class="text-lg sm:text-xl text-gray-600">Created At:</h2>
    <p class="text-base sm:text-lg text-gray-700"><%= @user.created_at.strftime('%B %d, %Y at %I:%M %p') %></p>
  </div>

  <div class="mt-6 flex justify-center space-x-4">
    <%= link_to "Edit User", edit_admin_user_path(@user), class: "bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition duration-150" %>
    <%= link_to "Delete User", admin_user_path(@user), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this user?" }, class: "bg-red-600 text-white px-4 py-2 rounded-lg hover:bg-red-700 transition duration-150" %>
    <%= link_to "Back to Users", admin_users_path, class: "bg-green-500 text-white px-4 py-2 rounded-lg hover:bg-gray-400 transition duration-150" %>
  </div>
</div>