config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root to: "trader/stocks#index"

  namespace :admin do
    root to: 'dashboard#index', as: :root

    resources :dashboard, only: [:index]
    resources :users, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      collection do
        get :pending_approvals
      end
      member do
        patch :approve
      end
    end
    resources :transactions, only: [:index]
  end

  namespace :trader do
    resources :users, only: [:show, :index] do
      resources :stocks, only: [:index]
      resources :transactions, only: [:index, :new, :create]
    end
  end

  match "*unmatched", to: "errors#not_found", via: :all

  match "*unmatched", to: "errors#not_found", via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :user

  validates :symbol, presence: true
  validates :balance, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user

  validates :symbol, presence: true
  validates :is_buy, inclusion: [true, false]
  validates :quantity, presence: true, comparison: {  other_than: 0 }
  validates :price, presence: true
  validates :total_price, presence: true

   def self.ransackable_attributes(auth_object = nil)
    ["symbol", "is_buy", "created_at", "quantity", "price", "total_price"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  has_many :transactions, dependent: :destroy
  has_many :stocks, dependent: :destroy

  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 6 }, allow_blank: true
  validates :name, presence: true

  def active_for_authentication?
    super && is_approved?
  end

  def inactive_message
    is_approved? ? super : :not_approved
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  layout 'admin'

  def index
    @all_users = User.all
    @pending_users = User.where(is_approved: false).where(is_admin: false)
    @user = current_user
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout "admin"
  before_action :set_user, only: [:show, :edit, :update, :destroy, :approve]
  before_action :authorize_admin!
  rescue_from ActiveRecord::RecordNotFound, with: :user_not_found

  def index
    @all_users = User.where(is_admin: false).order(created_at: :desc).page(params[:page]).per(5)
    @total_users = User.where(is_approved: true).where.not(confirmed_at: nil).count
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.is_approved = true
    if @user.save
      redirect_to admin_users_path, notice: "User successfully created"
    else
      render :new, status: :unprocessable_entity, alert: "Failed creating user, try again"
    end
  end

  def show; end

  def edit; end

  def update
    @user.assign_attributes(user_params)
    @user.skip_reconfirmation!
    if @user.save
      redirect_to admin_user_path(@user), notice: "User updated successfully"
    else 
      render :edit, status: :unprocessable_entity, alert: "Unable to update user"
    end
  end
  
  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice: "User deleted"
    else
      redirect_to admin_users_path, alert: "Failed to delete user"
    end
  end

  def pending_approvals
    @pending_users = User.where(is_approved: false).where.not(confirmed_at: nil)
  end
  
  def approve  
    @user.update(is_approved: true)
    UserMailer.with(user: @user).approval_email.deliver_now
    redirect_to pending_approvals_admin_users_path, notice: "User approved and can now log in"
  end

  private
  
  def user_params
    permitted = params.require(:user).permit(:name, :email, :password, :password_confirmation)
    if permitted[:password].blank?
      permitted.delete(:password)
      permitted.delete(:password_confirmation)
    end
    permitted
  end
  
  def set_user
    @user = User.find(params[:id])
  end

  def user_not_found
    redirect_to admin_users_path, alert: "An error occurred while trying to find the information you're getting" 
  rescue StandardError => e
    redirect_to admin_users_path, alert: "An error occurred while trying to find the user."
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :is_admin])
  end
  
  def after_sign_in_path_for(current_user)
    current_user.is_admin? ? admin_root_path : root_path
  end

  def set_stock_data
    FmpApi.get_stock_info if !defined?($stock_data)
  end

  def authorize_admin!
    unless current_user.present? && current_user.is_admin? && current_user.is_approved?
    redirect_to root_path, alert: "You are not authorized to access this administrative area."
    end
  end
  
  def trader_check
    if current_user.is_admin
      redirect_to admin_root_path, alert: "redirected, for traders only"
    end
  end

  
  def trader_check
    if current_user.is_admin
      redirect_to admin_root_path, alert: "redirected, for traders only"
    end
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  before_action :authenticate_user!
  def not_found
  end
end

app/controllers/trader/stocks_controller.rb
class Trader::StocksController < ApplicationController
  before_action :authenticate_user!
  before_action :trader_check
  layout "trader"

  def index
    @stocks = current_user.stocks
  end
end

app/controllers/trader/users_controller.rb
class Trader::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_stock_data
  before_action :trader_check
  layout "trader"
  def show; end

  def index
    redirect_to trader_user_path(current_user)  
  end
end 

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/transactions_helper.rb
module Admin::TransactionsHelper
end

app/helpers/admin/user_helper.rb
module Admin::UserHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/trader/stocks_helper.rb
module Trader::StocksHelper
end

app/helpers/trader/transactions_helper.rb
module Trader::TransactionsHelper
end

app/helpers/trader/user_helper.rb
module Trader::UserHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= content_for(:title) || "Admin Dashboard" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'tailwind', media: 'all' %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-[#F5F5F5] min-h-screen flex flex-col">
    <nav class="bg-[#24135f] text-green-500 p-1 w-full h-20 sticky top-0 z-50 flex justify-between items-center">
      <%= link_to "StockPro", admin_root_path, class: "text-2xl font-bold text-white" %>

      <div class="flex space-x-6">
        <%= link_to "Dashboard", admin_root_path, class: "text-white hover:text-green-400" %>
        <%= link_to "User Management", admin_users_path, class: "text-white hover:text-green-400" %>
        <%= link_to "Pending Approval", pending_approvals_admin_users_path, class: "text-white hover:text-green-400" %>
        <%= link_to "Transactions", admin_transactions_path, class: "text-white hover:text-green-400" %>
      </div>
      
      <div class="flex items-center">
        <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "bg-red-500 text-white px-2 py-1 rounded-lg hover:bg-red-700"%>
      </div>
    </nav>

    <div class="container mx-auto mt-4 px-5 z-40">
      <% if flash[:notice] %>
        <div data-controller="fade-out" class="bg-green-500 text-center text-white p-4 rounded-md shadow-lg" role="alert">
          <span>✅ <%= flash[:notice] %></span>
        </div>
      <% elsif flash[:alert] %>
        <div data-controller="fade-out" class="bg-yellow-500 text-center text-white p-4 rounded-md shadow-lg" role="alert">
          <span>⚠️ <%= flash[:alert] %></span>
        </div>
      <% end %>

    </div>
    <main class="container mx-auto px-5 flex-grow">
      <%= content_for?(:main_content) ? yield(:main_content) : yield %>
    </main>

    <footer class="bg-gray-800 text-white py-4 mt-8">
      <div class="container mx-auto text-center text-sm">
        <p>&copy; <%= Time.now.year %> StockTradingApp. All rights reserved.</p>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Stock Trading App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
  </head>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="/src/style.css" rel="stylesheet">
  </head>

  
  <body>
      <p class="notice flex flex-col text-center font-black-500 text-base font-medium mx-auto bg-green-100"><%= notice %></p>
      <p class="alert flex flex-col text-center font-black-500 text-base font-medium mx-auto bg-red-100"><%= alert %></p>
      <main class="container mx-auto px-5 flex">
      <%= yield %>
      </main>
  </body>
</html>

app/views/layouts/trader.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Stock Trading App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>

    <nav class="flex items-center justify-between px-6 py-3 bg-black text-white">

      <div class="flex flex-col">
        <span class="text-2xl font-bold">Stock Pro</span>
        <div class="text-sm text-gray-400">
          <span><%= current_user.email %></span> |
          <span>Balance: $<%= current_user.usd_balance.round(2) %></span>
        </div>
      </div>

      <div class="flex items-center space-x-4 text-sm">
        <%= link_to "Trade", trader_user_path(current_user), class: "hover:text-gray-300" %>
        <%= link_to "Stocks", trader_user_stocks_path(current_user), class: "hover:text-gray-300" %>
        <%= link_to "Transactions", trader_user_transactions_path(current_user), class: "hover:text-gray-300" %>
        <%= button_to "Log out", destroy_user_session_path, method: :delete,
            class: "text-red-400 hover:text-red-300 bg-transparent p-0 border-none" %>
      </div>
    </nav>

    <p class="notice flex flex-col text-center font-black-500 text-base font-medium mx-auto bg-green-100"><%= notice %></p>
    <p class="alert flex flex-col text-center font-black-500 text-base font-medium mx-auto bg-red-100"><%= alert %></p>

      
    <main class="max-w-6xl mx-auto mt-28 px-6 py-6 bg-white/5 text-black rounded-xl shadow-lg">
      <%= yield %>
    </main>
  </body>
</html>